#################################################################################
### HOME ########################################################################
#################################################################################

### GET home page
GET http://localhost:8080/

### GET ping-pong
GET http://localhost:8080/ping

##################################################################################
### USERS ########################################################################
##################################################################################

### GET users data
GET http://localhost:8080/users

### GET user data
GET http://localhost:8080/users/53d57b05-d4d1-11ef-a3fb-0242ac140002

################################################################################
### CSV ########################################################################
################################################################################

