#################################################################################
### HOME ########################################################################
#################################################################################

### GET home page
GET http://localhost:8080/

### GET ping-pong
GET http://localhost:8080/ping

##################################################################################
### USERS ########################################################################
##################################################################################

### GET users whit sensitive data
GET http://localhost:8080/users/sensitive

### GET users without sensitive data
GET http://localhost:8080/users

### GET all user data
GET http://localhost:8080/users/53d5d122-d4d1-11ef-a3fb-0242ac140002

### POST user
POST http://localhost:8080/users
Content-Type: application/json

{
    "password": "0987",
    "email": "test@test.com",
    "rol": "admin"
}

### PUT user
PUT http://localhost:8080/users/df929f56-e251-11ef-9af7-0242ac140002
Content-Type: application/json

{
    "name": "Rebeca",
    "password": "765",
    "email": "rebeca@test.com",
    "rol": "client"
}

### PATCH user
PATCH http://localhost:8080/users/df929f56-e251-11ef-9af7-0242ac140002
Content-Type: application/json

{
    "rol": "admin"
}

### DELETE user
DELETE http://localhost:8080/users/fe5165a4-e23c-11ef-9af7-0242ac140002

### GET users CSV
GET http://localhost:8080/users/csv?headers=["id","email","rol"]&limit=5&name=aaa

### GET users PDF
GET http://localhost:8080/users/pdf?headers=["id","email","rol"]&limit=5&name=aaa